// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPsc-D9lPU_ah-i7YYtIHpQRpWvVHNT6A',
    appId: '1:720566509867:web:b44d9b633b40792578a56e',
    messagingSenderId: '720566509867',
    projectId: 'debateme-15b75',
    authDomain: 'debateme-15b75.firebaseapp.com',
    storageBucket: 'debateme-15b75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAilXtjmZzq8zDWxlqoJrpocTSF5Pn-cD8',
    appId: '1:720566509867:android:c3eec8e5ba83543178a56e',
    messagingSenderId: '720566509867',
    projectId: 'debateme-15b75',
    storageBucket: 'debateme-15b75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWoUaSLfPN69kwEqsrV9UUugtWIm6A6BQ',
    appId: '1:720566509867:ios:03fc9caa6578430c78a56e',
    messagingSenderId: '720566509867',
    projectId: 'debateme-15b75',
    storageBucket: 'debateme-15b75.firebasestorage.app',
    iosBundleId: 'com.debateme.debateme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWoUaSLfPN69kwEqsrV9UUugtWIm6A6BQ',
    appId: '1:720566509867:ios:03fc9caa6578430c78a56e',
    messagingSenderId: '720566509867',
    projectId: 'debateme-15b75',
    storageBucket: 'debateme-15b75.firebasestorage.app',
    iosBundleId: 'com.debateme.debateme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPsc-D9lPU_ah-i7YYtIHpQRpWvVHNT6A',
    appId: '1:720566509867:web:140d1c7707e3eda878a56e',
    messagingSenderId: '720566509867',
    projectId: 'debateme-15b75',
    authDomain: 'debateme-15b75.firebaseapp.com',
    storageBucket: 'debateme-15b75.firebasestorage.app',
  );
}
